language: php
php:
  - '5.6'
  - hhvm-3.18
branches:
  only:
    - master
env:
  global:
before_script:
  - curl -sSfL -o ~/.phpenv/versions/hhvm/bin/phpunit https://phar.phpunit.de/phpunit-5.7.phar
after_success:
  - ./deploy.sh 